# Generated by Django 5.1.1 on 2024-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
