# Generated by Django 5.1.1 on 2024-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='reg_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
